server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      maximum-pool-size: 10
      max-lifetime: 28500000 #DB WAIT_TIMEOUT -> 28800 (28800000)
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    root: info
    org.hibernate.SQL: info