server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/item_value_checker_user
    username: root
    password: asdqwe123
    hikari:
      maximum-pool-size: 10
      max-lifetime: 28500000 #DB WAIT_TIMEOUT -> 28800 (28800000)

  redis:
    host: localhost
    port: 6378
    password: asdqwe123

logging:
  level:
    root: info
    org.hibernate.SQL: info