server:
  port: 8080

spring:
  profiles:
    include: datasource
    group:
      dev: dev
      local: local, sql-init

  datasource:
    hikari:
      maximum-pool-size: 10
      max-lifetime: 28500000 #DB WAIT_TIMEOUT -> 28800 (28800000)

  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false

logging:
  level:
    root: error
    org.hibernate.SQL: error